a = int(input("Enter number1 :\t"))
b = int(input("Enter number2 :\t"))
print('Sum :',(a+b))
print('Sub :',(a-b))
print('Multiplication :',(a*b))
print('Division :',(a/b))
print('Floor Division :',(a//b))
print('Modulous :',(a%b))
print('Power :',(a**b))